name: Build wii-u-gc-adapter

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/steamdeckhomebrew/holo-base:latest

    steps:
      - name: install-git
        run: pacman -Sy --noconfirm git

      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: prepare
        run: ./scripts/prepare-holo.sh

      - name: build
        run: ./scripts/build.sh

      - name: package
        run: ./scripts/package.sh

      - uses: actions/upload-artifact@v4
        with:
          name: "dist-tar"
          path: "steam-deck-gc-adapter.tar.gz"
